### ISSUE TITLE
简单明了，非常感谢！我用Python3.5在win7上面写入时报错UnicodeDecodeError: 'gbk' codec can't decode byte

### ISSUE THREAD

**Issue by hulkbai** [jinixin/upload-demo#1]
已将读写方式改为二进制解决
with open('./upload/%s%s' % (task, ext), 'wb') as target_file:  # 创建新文件
        while True:
            try:
                filename = './upload/%s%d' % (task, chunk)
                source_file = open(filename, 'rb')  # 按序打开每个分片

**Comment by jinixin** [comment]
我看了下，原因可能是：

    upload_file = request.files['file']
    upload_file.save('./upload/%s' % filename)  # 保存分片到本地

其中save方法的定义：

    def save(self, dst, buffer_size=16384):
        from shutil import copyfileobj
        close_dst = False
        if isinstance(dst, string_types):
            dst = open(dst, 'wb')
            close_dst = True
        try:
            copyfileobj(self.stream, dst, buffer_size)
        finally:
            if close_dst:
                dst.close()

save方法使用了二进制方式写入，这可能会对Windows下的操作有些影响。

谢谢你的反馈，我已经修改了源码和README文件。 ^ _ ^
