### ISSUE TITLE
文件名乱码

### ISSUE THREAD

**Issue by CharlieLio** [jinixin/upload-demo#2]
下载到服务器上之后文件名乱码了，如何控制修改文件名呢？比如页面选择上传的时候把原文件名记录下来，等服务器下载好之后在进行重命名

**Comment by jinixin** [comment]
你好，我之前没考虑到这个问题，合并分片时直接使用框架的task_id拼接文件名，所以是个乱码。真实文件名可以通过框架的“file.source['name']”来获取。
谢谢你的反馈，我已经更新了源码和README。
